all:
	cd libs && make
	cd apps && make
	cd ld && make
	cd init && make

install:
	cd libs && make install
	cd apps && make install
	cd ld && make install
	cd init && make install

clean:
	cd libs && make clean
	cd apps && make clean
	cd ld && make clean
	cd init && make clean
