all:
	cd libs && make
	cd apps && make
	cd dl && make

install:
	cd libs && make install
	cd apps && make install
	cd dl && make install

clean:
	cd libs && make clean
	cd apps && make clean
	cd dl && make clean